### ISSUE TITLE
update from node 16 to 20

### ISSUE THREAD

**Issue by mishraomp** [shrink/actions-docker-registry-tag#32]
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: shrink/actions-docker-registry-tag@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by shrink** [comment]
Fixed in https://github.com/shrink/actions-docker-registry-tag/pull/33
